apiVersion: v1
kind: Service
metadata:
  name: flowise-service
  namespace: flowise
  labels:
    app: flowise
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: flowise
  type: LoadBalancer
